#!/bin/bash
if [ -d "/etc/squid/" ]; then
    payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
	payload="/etc/squid3/payload.txt"
fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "เพิ่ม Host ให้ Squid Proxy" ; tput sgr0
if [ ! -f "$payload" ]
then
	echo "" ; echo -e "\033[1;31m[ผิดพลาด]\033[1;33m เพิ่ม Host ไม่สำเร็จ: ไม่พบไฟล์ $payload — Squid Proxy อาจยังไม่ได้ติดตั้ง กรุณาติดตั้ง Squid ก่อน\033[0m" ; tput sgr0
	exit 1
else
	tput setaf 2 ; tput bold ; echo ""; echo "โดเมนปัจจุบันในไฟล์ $payload:" ; tput sgr0
	tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0
	read -p "พิมพ์โดเมนที่ต้องการเพิ่มในรายการ: " host
	if [[ -z $host ]]
	then
		echo "" ; echo -e "\033[1;31m[ผิดพลาด]\033[1;33m เพิ่มโดเมนไม่สำเร็จ: ไม่ได้กรอกโดเมน — กรุณากรอกโดเมนที่ขึ้นต้นด้วยจุด เช่น .example.com\033[0m" ; echo "" ; tput sgr0
		exit 1
	else
		if [[ `grep -c "^$host" $payload` -eq 1 ]]
		then
			echo "" ; echo -e "\033[1;31m[ผิดพลาด]\033[1;33m เพิ่มโดเมนไม่สำเร็จ: โดเมน $host มีอยู่ในไฟล์ $payload แล้ว — ไม่ต้องเพิ่มซ้ำ\033[0m" ; echo "" ; tput sgr0
			exit 1
		else
			if [[ $host != \.* ]]
			then
				echo "" ; echo -e "\033[1;31m[ผิดพลาด]\033[1;33m เพิ่มโดเมนไม่สำเร็จ: โดเมนต้องขึ้นต้นด้วยจุด (.) — เช่น .phreaker56.xyz\033[0m" ; echo "ไม่จำเป็นต้องเพิ่ม subdomain ของโดเมนที่มีอยู่ในไฟล์แล้ว" ; echo "เช่น ไม่ต้องเพิ่ม recargawap.claro.com.br" ; echo "หากโดเมน .claro.com.br อยู่ในไฟล์อยู่แล้ว" ; echo ""; tput sgr0
				exit 1
			else
				echo "$host" >> $payload && grep -v "^$" $payload > /tmp/a && mv /tmp/a $payload
				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "อัปเดตไฟล์ $payload แล้ว เพิ่มโดเมนเรียบร้อย:" ; tput sgr0
				tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0
				if [ ! -f "/etc/init.d/squid3" ]
				then
					service squid3 reload
				elif [ ! -f "/etc/init.d/squid" ]
				then
					service squid reload
				fi
				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "รีโหลด Squid Proxy เรียบร้อยแล้ว!" ; echo "" ; tput sgr0
				exit 1
			fi
		fi
	fi
fi