#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mกรุณารอสักครู่ \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mกรุณารอสักครู่ \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/versao ]] && rm /home/versao

  [[ -e /tmp/att ]] && rm /tmp/att

	wget -c -P /home https://raw.githubusercontent.com/kiritosshxd/SSHPLUS/master/Install/versao

	[[ -f "/home/versao" ]] && mv /home/versao /tmp/att

	[[ ! -e /bin/versao ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e "                              \033[1;31mBy kiritosshxd\033[1;36m"

echo -e "   SSHPlus" | figlet

echo " "

echo -e "   \033[1;32mกำลังตรวจสอบอัปเดตที่มี\033[0m\n"

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31m[ผิดพลาด]\033[1;33m ตรวจสอบอัปเดตไม่สำเร็จ: ดาวน์โหลดไฟล์เวอร์ชันไม่ได้ เช็คอินเทอร์เน็ตของเซิร์ฟเวอร์\033[0m\n"

	echo -ne "\033[1;33m กด \033[1;31mENTER \033[1;33mเพื่อกลับ\033[1;32mเมนู!\033[0m"; read

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/versao| sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     สคริปต์เป็นเวอร์ชันล่าสุดอยู่แล้ว!\033[1;32m\n"

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;33m ข้อมูลเพิ่มเติม \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@kiritosshxd\n"

  echo -ne " \033[1;33m กด \033[1;31mENTER \033[1;33mเพื่อกลับ\033[1;32mเมนู!\033[0m"; read

  menu

} || {

  echo -e "  \033[1;36mมีอัปเดตเวอร์ชันใหม่พร้อมให้ติดตั้ง!\033[1;33m\n"

  echo -e "  \033[1;33mข้อมูลเพิ่มเติม \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@kiritosshxd\n"

  echo -e "  \033[1;32mรายละเอียดการอัปเดต:\033[0m\n"

  while read linha; do

    echo -e "  \033[1;37m- \033[1;33m$linha"

  done < "/tmp/att"

  echo " "

  echo -ne "  \033[1;32mต้องการอัปเดตหรือไม่ \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read res

  if [[ "$res" = s || "$res" = S ]];then

    echo -e "\n\033[1;32m  กำลังเริ่มอัปเดต..."

    sleep 3

    if ! wget https://raw.githubusercontent.com/kiritosshxd/SSHPLUS/master/Plus > /dev/null 2>&1; then

      echo -e "\n\033[1;31m[ผิดพลาด]\033[1;33m อัปเดตไม่สำเร็จ: ดาวน์โหลดไฟล์ไม่ได้ เช็คอินเทอร์เน็ตของเซิร์ฟเวอร์\033[0m\n"

      echo -ne "\033[1;33mกด \033[1;31mENTER \033[1;33mเพื่อกลับ\033[1;32mเมนู!\033[0m"; read

      menu

    fi

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mอัปเดตสคริปต์เรียบร้อยแล้ว\033[0m\n"

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;33mกด \033[1;31mENTER \033[1;33mเพื่อกลับ\033[1;32mเมนู!\033[0m"; read

    menu

  else

    menu

  fi

}

