#!/bin/bash
#====================================================
#	SCRIPT: LIMITER HEXPLUS MANAGER
#	DESENVOLVIDO POR:	lolyhexey
#	GITHUB:	https://github.com/lolyhexey/HEXPLUS
#====================================================
clear
database="/root/usuarios.db"
fun_multilogin() {
	(
		while read user; do
			[[ $(grep -wc "$user" $database) != '0' ]] && limit="$(grep -w $user $database | cut -d' ' -f2)" || limit='1'
			conssh="$(ps -u $user | grep sshd | wc -l)"
			[[ "$conssh" -gt "$limit" ]] && {
				pkill -u $user
			}
			[[ -e /etc/openvpn/openvpn-status.log ]] && {
				ovp="$(grep -E ,"$user", /etc/openvpn/openvpn-status.log | wc -l)"
				[[ "$ovp" -gt "$limit" ]] && {
					pidokill=$(($limit - $ovp))
					listpid=$(grep -E ,"$user", /etc/openvpn/openvpn-status.log | cut -d "," -f3 | head -n $pidokill)
					while read ovpids; do
						(
							telnet localhost 5555 <<-EOF
								kill $ovpids
							EOF
						) &>/dev/null &
					done <<<"$listpid"
				}
			}
		done <<<"$(awk -F: '$3 >= 1000 {print $1}' /etc/passwd)"
	) &
}
if [[ ! -e "$database" ]]; then
    echo -e "\033[1;31m[ผิดพลาด]\033[1;33m จำกัดจำนวนอุปกรณ์ตามฐานข้อมูลไม่ได้: ไม่พบไฟล์ฐานข้อมูลผู้ใช้ (usuarios.db) — กรุณาติดตั้งสคริปต์ใหม่หรือสร้างผู้ใช้ก่อน (จะใช้จำนวนอุปกรณ์เริ่มต้นเป็น 1)\033[0m"
fi
while true; do
    echo 'กำลังตรวจสอบ...'
	fun_multilogin > /dev/null 2>&1
	sleep 15s
done
