#!/bin/bash
#====================================================
#	@kiritosshxd
#====================================================
_lvk=$(wget -qO- https://kguza.net/sshplus-vip/Install/versao)
IP=$(wget -qO- ipv4.icanhazip.com)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
echo -e "$ipdovps" >/etc/IP
lst=$1 && lst1=$2 && lst2=$3 && key1=$4 && key2=crz
echo -e "Asia/Bangkok" >/etc/timezone
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1
[[ -z $lst1 ]] && {
	rm -rf $_Ink/list >/dev/null 2>&1 && cat /dev/null >~/.bash_history && history -c && exit 0
}
[[ ! -d /etc/SSHPlus ]] && mkdir /etc/SSHPlus
[[ ! -d /etc/SSHPlus/senha ]] && mkdir /etc/SSHPlus/senha
[[ ! -e /etc/SSHPlus/Exp ]] && touch /etc/SSHPlus/Exp
[[ ! -d /etc/SSHPlus/userteste ]] && mkdir /etc/SSHPlus/userteste
[[ ! -d /etc/SSHPlus/.tmp ]] && mkdir /etc/SSHPlus/.tmp
echo -e 'by: @KIRITO_SSH' >/usr/lib/sshplus && cat /usr/lib/sshplus >$lst2/licence && cat /usr/lib/sshplus > /etc/SSHPlus/.tmp/crazy
netstat -nplt | grep -w 'apache2' | grep -w '80' && sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf && service apache2 restart
[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
_dir1='/bin'
_dir2='/etc/SSHPlus'
_dir3='/usr/bin'
_dir4='/root'
_dir5='/auto/speed'
rm $_dir3/s
rm -rf $_dir4/$_dir5 
rm $_dir1/addhost $_dir1/delhost $_dir1/alterarsenha $_dir1/criarusuario $_dir1/expcleaner $_dir1/mudardata $_dir1/remover $_dir1/criarteste $_dir1/droplimiter $_dir1/alterarlimite $_dir1/ajuda $_dir1/sshmonitor $_dir1/badvpn $_dir1/userbackup $_dir1/instsqd $_dir1/otimizar $_dir1/menu $_dir1/speedtest $_dir1/banner $_dir1/senharoot $_dir1/reiniciarservicos $_dir1/reiniciarsistema $_dir1/attscript $_dir1/conexao $_dir1/delscript $_dir1/detalhes $_dir1/infousers $_dir1/verifatt $_dir1/limiter $_dir1/uexpired $_dir1/onlineapp $_dir1/swapmemory $_dir1/changeroot $_dir1/timereboot
rm $_dir2/cabecalho $_dir2/open.py $_dir2/proxy.py $_dir2/wsproxy.py >/dev/null 2>&1
_mdls=("addhost" "delhost" "alterarsenha" "criarusuario" "expcleaner" "mudardata" "remover" "criarteste" "droplimiter" "alterarlimite" "ajuda" "sshmonitor" "badvpn" "userbackup" "instsqd" "otimizar" "menu" "speedtest" "banner" "senharoot" "reiniciarservicos" "reiniciarsistema" "attscript" "conexao" "delscript" "detalhes" "infousers" "verifatt" "limiter" "uexpired" "cabecalho" "open.py" "proxy.py" "wsproxy.py" "onlineapp" "swapmemory" "changeroot" "timereboot" "setspeed.sh" "bw" ".chek" ".bw" "status")
for _arq in ${_mdls[@]}; do
	[[ -e $_dir1/$_arq ]] && rm $_dir1/$_arq >/dev/null 2>&1
	wget -c -P $_dir1 https://kguza.net/sshplus-vip/Modulos/$_arq
	chmod +x $_dir1/$_arq
	mkdir -p $_dir4/$_dir5
done
mv $_dir1/cabecalho $_dir1/open.py $_dir1/proxy.py $_dir1/wsproxy.py $_dir2
mv $_dir1/changeroot $_dir3
mv $_dir1/setspeed.sh $_dir3/setspeed
mv $_dir1/.bw $_dir1/status $_dir1/.chek $_dir4/$_dir5
./bw stop
mv $_dir1/bw $_dir3/s
chmod +x $_dir3/s
echo "    ┣  $_3nk "  > $_dir4/$_dir5/status
echo >> $_dir4/$_dir5/log
sed -i '/^$/d' $_dir4/$_dir5/log
_arq_host="/etc/hosts"
_host[0]="app.dtac.co.th"
_host[1]="www.opensignal.com"
_host[2]="kguza.net2"
_host[3]="KGUZA2"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done
[[ ! -e /etc/autostart ]] && {
	echo '#!/bin/bash
clear
#INICIO AUTOMATICO' >/etc/autostart
	chmod +x /etc/autostart
} || {
	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
		screen -r -S "$proc" -X quit	
done
	screen -wipe >/dev/null
	echo '#!/bin/bash
clear
#INICIO AUTOMATICO' >/etc/autostart
	chmod +x /etc/autostart
}
crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "@daily /bin/verifatt"
	echo "@reboot /etc/autostart"
	echo "* * * * * /etc/autostart"
	echo "0 */6 * * * /bin/uexpired"
) | crontab -
echo "$_lvk" | sed -n '1 p' | cut -d' ' -f2 >/bin/versao && cat /bin/versao >/home/sshplus
wget https://kguza.net/sshplus-vip/Install/jq-linux64 >/dev/null 2>&1
chmod +x jq-linux64 && mv jq-linux64 $(which jq)
service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart >/dev/null 2>&1
rm -rf $lst1/list >/dev/null 2>&1
