#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     เปิดใช้งานบอท SSH ทดลอง     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mกรอกโทเค็น\033[1;37m: "; read token
    cd $HOME/BOT
    screen -dmS bot_teste ./botssh $token > /dev/null 2>&1
    clear && echo "เปิดใช้งานบอทแล้ว"
} || {
    screen -r -S "bot_teste" -X quit
    clear && echo "ปิดบอทแล้ว"
}